# Generated by Django 5.1.4 on 2024-12-27 19:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('imgUrl', models.URLField()),
                ('kwaiLink', models.URLField()),
                ('tiktokLink', models.URLField()),
            ],
        ),
    ]
